version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: library_management_app
    restart: unless-stopped
    environment:
      PORT: 3030
      JWT_SECRET: secret_eeeh
      NODE_ENV: production
      DB_USERNAME: root
      DB_PASSWORD: test123
      DB_NAME: library_management
      DB_HOST: mysql
      DEBUG: '*,-babel,-express:*,-body-parser:*,-nodemon,-morgan,-sequelize,-sequelize:*'
      DEBUG_COLORS: true
      DEBUG_DEPTH: 10
    ports:
      - "3030:3030"
    depends_on:
       mysql:
         condition: service_healthy

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: library_management
    ports:
      - "3304:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptest123"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: