version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: library_management_app
    restart: unless-stopped
    environment:
      PORT: 3030
      JWT_SECRET: secret_eeeh
      NODE_ENV: production
      DB_USERNAME: root
      DB_PASSWORD: test123
      DB_NAME: library_management
      DB_HOST: mysql
      DEBUG: '*,-babel,-express:*,-body-parser:*,-nodemon,-morgan,-sequelize,-sequelize:*'
      DEBUG_COLORS: true
      DEBUG_DEPTH: 10
    ports:
      - "3030:3030"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: library_management_db
    environment:
      MYSQL_DATABASE: library_management
      MYSQL_ROOT_PASSWORD: test123
    ports:
      - "3304:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: